
name: 'update-citations'

on:
  schedule:
    - cron:  '48 03 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Setup git
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
    - name: Run python
      run: |
        python scripts/update_citations.py --push
